### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by radekkpl** [bartlomiej-stys/AsyncNet#1]
Hi. Is it possible to add broadcast feature? Sending message to all connected clients?

**Comment by bartlomiej-stys** [comment]
Hi, it's possible for TCP since it's connection-oriented protocol, but Udp is connectionless, so it's up to user of this library to define "connected" state. Let me know if you are interested in TCP or UDP.

**Comment by radekkpl** [comment]
I am using TCP. My one project is Server application which is reading data each 4 seconds from connected PLCs and making all actions and sending results to second project, which is only viewer application that comunicate with server and only receiving messages from it.
I am now using my own solution based on TCP, but I think our solution is more robust, because it is Async, so it will have no problem with to much clients connected. A aim creating these application for my company for internal using only.

**Comment by bartlomiej-stys** [comment]
Cool. I think I can add broadcast feature to AsyncNet.Tcp. I will let you know when it's done. It may take a few days, because I am currently working on this library only in my spare time.

**Comment by bartlomiej-stys** [comment]
@radekkpl 
Hi, please take a look at:
```csharp
IAsyncNetTcpServer.ConnectedPeers
IAsyncNetTcpServer.Broadcast
IAsyncNetTcpServer.BroadcastAsync
```
added in 1.2.0
