### ISSUE TITLE
Is there a clean way to use an SslStream here?

### ISSUE THREAD

**Issue by zedle** [bartlomiej-stys/AsyncNet#12]
Great library - just trying to figure out a clean way to add TLS without modifying the library. Is there a way you intended for this to be done or am I going to need to make changes?

**Comment by zedle** [comment]
I assume the idea was to tap into the Stream provided - but that burns the send queue, protocol framing, etc.

Is there no way to maintain those and use SSL?

**Comment by bartlomiej-stys** [comment]
Hi,
If you look at the config class. You can add SSL / TLS support there:
```csharp
    public class AsyncNetTcpServerConfig
    {
        public Func<IRemoteTcpPeer, IProtocolFrameDefragmenter> ProtocolFrameDefragmenterFactory { get; set; } = (_) => MixedDefragmenter.Default;

        public TimeSpan ConnectionTimeout { get; set; } = TimeSpan.Zero;

        public int MaxSendQueuePerPeerSize { get; set; } = -1;

        public IPAddress IPAddress { get; set; } = IPAddress.Any;

        public int Port { get; set; }

        public Action<TcpListener> ConfigureTcpListenerCallback { get; set; }

        public bool UseSsl { get; set; }

        public X509Certificate X509Certificate { get; set; }

        public RemoteCertificateValidationCallback RemoteCertificateValidationCallback { get; set; } = (_, __, ___, ____) => true;

        public EncryptionPolicy EncryptionPolicy { get; set; } = EncryptionPolicy.RequireEncryption;

        public Func<TcpClient, bool> ClientCertificateRequiredCallback { get; set; } = (_) => false;

        public Func<TcpClient, bool> CheckCertificateRevocationCallback { get; set; } = (_) => false;

        public SslProtocols EnabledProtocols { get; set; } = SslProtocols.Default;
    }
```
You can pass this config to the server constructor. Set the `UseSsl` property to true and provide your SSL certificate - setting the `X509Certificate ` property. You can also set `EncryptionPolicy` and override any of the callbacks to configure your certificate rules if you want. The server will use SslStream behind the scenes. Let me know if this scenario is ok for you. I'm working on 2.0 version of this library to improve performance and add TCP connection pool. Any suggestions on how to make this library better and more developer friendly are appreciated.

**Comment by zedle** [comment]
Ahh alright perfect.. thank you.

Looking forward to that 2.0 version!

**Comment by zedle** [comment]
Only suggestion I'd make is perhaps adding an example in the readme/wiki that shows a working example. I was able to get it going by the way, thanks again.

**Comment by bartlomiej-stys** [comment]
Thanks for the suggestion. I will try to provide more examples with 2.0 release
