### ISSUE TITLE
Can I ask how to implement custom deframing

### ISSUE THREAD

**Issue by radekkpl** [bartlomiej-stys/AsyncNet#13]
I am now implementing this library into my project and would like to know how to implement custom deframing.
Each message from server starts with character "<"
Each message from server ends with character ">"

So in custom deframing factory I will need to create some buffer.
If data arrives, then attach that data into end of the buffer(if is not empty)
Then check if contains ">". If no, leave data in buffer for future adding
If yes, split the message from "<"(this char should be always at the begining of the buffer, because it is always first received char) to ">" and create the frame.

Currently with using basic tcpclient I am using concurentqueue where TCPclient pushes the messages and the application tries to read messages in 5s cycle by timer:

            Dim tel As String = Encoding.Unicode.GetString(arg.Data)
            If PLCpureMessagesBuffer = String.Empty Then
                PLCpureMessagesBuffer = tel
            Else
                PLCpureMessagesBuffer = PLCpureMessagesBuffer.Insert(PLCpureMessagesBuffer.Length, tel)
            End If

            While PLCpureMessagesBuffer.Contains(">")
                Dim posiceEnd As Integer = PLCpureMessagesBuffer.IndexOf(">")
                Dim PLCmesage As String = PLCpureMessagesBuffer.Substring(0, posiceEnd + 1)
                PLCpureMessagesBuffer = PLCpureMessagesBuffer.Remove(0, posiceEnd + 1)
                PLCmessages.Enqueue(PLCmesage.Replace("<", "").Replace(">", ""))
            End While

**Comment by bartlomiej-stys** [comment]
Hi. I'm not really familiar with Visual Basic so I have only C# code for you.

You can just implement `IMixedDefragmentationStrategy`:

```csharp
public class AngleBracketsStrategy : IMixedDefragmentationStrategy
{
    public int ReadBufferLength => 512;

    public MixedDefragmentationStrategyReadType ReadType => 
        MixedDefragmentationStrategyReadType.ReadDefault;

    public int GetFrameLength(byte[] buffer, int dataLength)
    {
        for (var i = 0; i < buffer.Length; i++)
        {
            if (buffer[i] == '>')
            {
                // i + 2 is for UTF-16/Unicode and i + 1 will be for UTF-8
                return i + 2;
            }
        }
        // 0 means we cannot determine frame length yet
        return 0;
    }
}
```
Then plug it into `MixedDefragmenter` and create your client with proper config:
```csharp
var createDefragmenterLazy = new Lazy<IProtocolFrameDefragmenter>(()
    => new MixedDefragmenter(new AngleBracketsStrategy()));

var config = new AsyncNetTcpClientConfig()
{
    TargetPort = 5555,
    TargetHostname = "127.0.0.1",
    ProtocolFrameDefragmenterFactory = (_) => createDefragmenterLazy.Value
};

var tcpClient = new AsyncNetTcpClient(config);
```

Now each frame will be your message plus brackets `<>`:

```csharp
tcpClient.FrameArrived += (sender, eventArgs) =>
{
    var message = Encoding.Unicode.GetString(eventArgs.FrameData);

    Console.WriteLine(message);
};

await tcpClient.StartAsync(CancellationToken.None);
```

**Comment by radekkpl** [comment]
Thanks. Csharp is OK.

So basicaly Deframing strategy is only to determine where in the stream is real end and return it from function getframelength or 0 to try it next time, more data is available.
It is nice.
