### ISSUE TITLE
Async Tcp Client for .NETStandard 2, Xamarin.Forms?

### ISSUE THREAD

**Issue by dinobu** [bartlomiej-stys/AsyncNet#2]
Hi,

I am working an a project that with following requirements

1. Has to use TCP/IP to send and receive messages
2. The messages are in form of byte[]
3. I must have method like GetDataAsync() which will use your Async TcpClient to write asynchronously the message (send it to a server at an IP/Port) AND will then read response from that server
4. Once entire response is received, the response will then be converted into a string
5. The string will be parsed and used to create a List models which is then displayed in a ListView
6. This is to be done using .NETStandard 2.0 Xamarin Forms application.
7. Based on above, is this library helpful in such situation?

Much appreciated,

**Comment by bartlomiej-stys** [comment]
Hi, Sure, This library works with .NET Standard 2.0, so it can be used with Xamarin.Forms. GetDataAsync() can be achieved using TaskCompletionSource. For sending strings I recommend using length prefixed defragmentation/deframing strategy. 

This library doesn't have decent documentation yet, but I will provide some examples.

**Comment by dinobu** [comment]
I would highly appreciate samples or documentation, thank you.  My messages so hand length/fragmentation but my main concern is following 

I need to asynchronously:
1. Connect Async
2. Send WriteAsync request
3. While DataAvailable, loop and ReadAsync response until no more
4. Once entire response is back, I need to parse it into a List<MyModelType>.

Currently, I have this all in a single method GetDataAsync() that returns List<MyModelType> .

**Comment by bartlomiej-stys** [comment]
It may take a few days, because I'm working on this library only in my spare time, but I will provide some examples including Xamarin one and improve documentation. I will let you know when it's ready.

It requires a little work and usage of TaskCompletionSource, but it can be done already within a single asynchronous method call as yours - GetDataAsync(). Perhaps I will make some enhancements to make this even easier.

**Comment by dinobu** [comment]
> It may take a few days, because I'm working on this library only in my spare time, but I will provide some examples including Xamarin one and improve documentation. I will let you know when it's ready.
> 
> It requires a little work and usage of TaskCompletionSource, but it can be done already within a single asynchronous method call as yours - GetDataAsync(). Perhaps I will make some enhancements to make this even easier.

I have created a SO post with explanation of my issue and how I resolved it here [.](https://stackoverflow.com/questions/54892579/networkstream-readasync-and-writeasync-hang-infinitelly-when-using-cancellationt)  I think it will help understand.  At this stage, Id say that my problem is that my GetDataAsync is doning so many things such as creating message, writAsync, readAsync, ParseMessage.

**Comment by bartlomiej-stys** [comment]
I'm preparing some examples. Do you have acceess to server code? Can you change it? If not - do you have any documentation on how the server responds with data? I see you used "DataAvailable" here which is not always a good idea - your code may stop working as expected under different network conditions. See why: https://stackoverflow.com/a/4261500/6440521

I've updated the library to 1.2.0 which supports awaitaible client - look at the updated readme for basic usage. I will add some more working examples soon.

**Comment by dinobu** [comment]
No access to server code, so no way to change it.
The server response will always be up to maybe 1000 characters long.
The response is triggered by request message that will always be up to 100 characters long.
The messages do have Length field as 1st field, then message Id field etc
Each request comes after response, so it is user triggered.  User taps on a button, this sends request which returns response, that happens in one shot.
After while loop processes response, the data is parsed to build a list.
Thanks for sharing that link, I have read it and added call await Task.Delay(1) at the bottom of while loop as in one of suggested answers.  Will also check the read me.
Thanks

**Comment by khanziaullah** [comment]
I am working on a BizTalk 2013 project. I can go as high as .Net Framework 4.7.2. I am stuck with using Visual Studio 2013. When I add nuget package to my solution I see error like below:

Could not install package 'AsyncNet.Tcp 1.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is there a way you could release this project for .net 4.7.2 as well please?

**Comment by bartlomiej-stys** [comment]
@khanziaullah 
Hi, I've opened new issue and released new version: https://github.com/bartlomiej-stys/AsyncNet/issues/3
