### ISSUE TITLE
Support for .NET Framework 4.5 and above

### ISSUE THREAD

**Issue by bartlomiej-stys** [bartlomiej-stys/AsyncNet#3]
I am working on a BizTalk 2013 project. I can go as high as .Net Framework 4.7.2. I am stuck with using Visual Studio 2013. When I add nuget package to my solution I see error like below:

Could not install package 'AsyncNet.Tcp 1.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is there a way you could release this project for .net 4.7.2 as well please?

_Originally posted by @khanziaullah in https://github.com/bartlomiej-stys/AsyncNet/issues/2#issuecomment-472129546_

**Comment by bartlomiej-stys** [comment]
@khanziaullah
I've added support for .NET Framework in 1.2.3. Check it out.

Visual Studio 2013 is quite old. Make sure you follow these steps here: https://stackoverflow.com/a/25844391/6440521

which is to install this NuGet extension for visual studio 2013 before installing AsyncNet library:

https://marketplace.visualstudio.com/items?itemName=NuGetTeam.NuGetPackageManagerforVisualStudio2013

Make sure you have updated your nuget and VS to the newest version.

**Comment by khanziaullah** [comment]
That fixed it. Thanks much.
