### ISSUE TITLE
AsyncNet.Tcp does not have a strong name

### ISSUE THREAD

**Issue by khanziaullah** [bartlomiej-stys/AsyncNet#4]
CSC : error CS1577: Assembly generation failed -- Referenced assembly 'AsyncNet.Tcp' does not have a strong name

I've figured out a temporary fix using ildasm. Would be nice to have a signed assembly.

**Comment by bartlomiej-stys** [comment]
Thanks for reporting this issue. Take a look at 1.2.4. Should be signed now
