### ISSUE TITLE
EventSourceException while processing event "NewID": No Free Buffers available from the operating system (e.g. event rate too fast).

### ISSUE THREAD

**Issue by khanziaullah** [bartlomiej-stys/AsyncNet#5]
![image](https://user-images.githubusercontent.com/7236556/54265240-dad23480-459a-11e9-9cb5-8364777c9fdb.png)

Surprisingly I am seeing a lot of these errors now. Not sure if it's related to DataFlow and TPL library/async programming discussed [here](https://social.msdn.microsoft.com/Forums/en-US/335e0302-0ab6-42e2-b514-63f12d975252/eventsourceexception-message-not-thrown-during-dataflowblocksendasync?forum=tpldataflow)

Also, I am not receiving any more _FrameArrived_ and _ConnectionEstablished_ events. 

I tried a hello world with the last enhancement and it seems to be working fine. 

Please feel free to close it as not an issue if it's not the library.

**Comment by bartlomiej-stys** [comment]
If you could post some example code or steps to reproduce this issue I might be able to verify.

**Comment by khanziaullah** [comment]
My bad. I did not deploy System.Threading.Tasks.Dataflow.dll to gac. Thanks for your quick response.
