### ISSUE TITLE
e.RemoteTcpPeer.Disconnect(AsyncNet.LocalShutdown) throws TaskCanceledException. Need a graceful way to disconnect

### ISSUE THREAD

**Issue by khanziaullah** [bartlomiej-stys/AsyncNet#7]
![image](https://user-images.githubusercontent.com/7236556/55666932-324e8200-5873-11e9-8034-0bb960100820.png)

I am seeing the above error. On this line I am done sending the response back to the front end and want to disconnect. Which throws a TaskCanceledException. Is there a better way to disconnect a client?

**Comment by khanziaullah** [comment]
![image](https://user-images.githubusercontent.com/7236556/55666976-cddff280-5873-11e9-834b-3752f0699e1f.png)
This same line is giving me an object disposed exception. The CancellationTokenSource object has been disposed. Would you know what could be causing this?

I am not cancelling any of my operations at the moment. Should my code handle task cancellations by passing the cts or the token?

**Comment by bartlomiej-stys** [comment]
Thanks for opening this issue. Will look into it

**Comment by bartlomiej-stys** [comment]
Which version of the library are you using? I couldn't reproduce this issue. It's very unlikely that the Disconnect will throw an exception with the newest version of the library (currently 1.2.5). Look at the implementation:
```csharp
        /// <summary>
        /// Disconnects this peer/client
        /// </summary>
        /// <param name="reason">Disconnect reason</param>
        public virtual void Disconnect(ConnectionCloseReason reason)
        {
            try
            {
                this.connectionCloseReason = reason;
                this.cancellationTokenSource.Cancel();
            }
            catch (Exception ex)
            {
                this.exceptionHandler?.Invoke(new RemoteTcpPeerExceptionEventArgs(this, ex));
                return;
            }
        }
```
Please update your library to 1.2.5 and let me know if this resolved your issue.
If the issue is still occurring on 1.2.5 please upload some example code that reproduces this issue, so I can verify.

**Comment by khanziaullah** [comment]
I was my custom application and had break on Exceptions setting TaskCanceledException on.
![image](https://user-images.githubusercontent.com/7236556/56089020-9ee80300-5ea9-11e9-9b35-6a4fdc8def25.png)

A debug session with these exceptions checked in Exception Settings should simulate the behavior.

**Comment by bartlomiej-stys** [comment]
Currently this behavior cannot be avoided. I think I would need to rewrite entire library to avoid those exceptions. Actually it is considered a good practice to throw and catch those exceptions when writing async code:
https://stackoverflow.com/questions/24559416/is-catching-taskcanceledexception-and-checking-task-canceled-a-good-idea
https://devblogs.microsoft.com/premier-developer/recommended-patterns-for-cancellationtoken/
